name: Pipeline de build e deploy

on:
  push:
    branches:
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Testando github actions"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #commit-message: "feat: add new feature"
          #title: "feat: add new feature"
          #body: "feat: add new feature"
          #base: master
          branch: master
          #delete-branch: true
          #labels: "feature"
          #reviewers: "danielvazmartins"
