name: Pipeline de build e deploy

on:
  push:
    branches:
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Testando github actions"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v7
